Reorganized the code a bit.

diff --git a/bin/argbash b/bin/argbash
--- a/bin/argbash
+++ b/bin/argbash
@@ -9,11 +9,13 @@ version=2.5.1
 # DEFINE_SCRIPT_DIR()
 # ARG_POSITIONAL_SINGLE([input],[The input template file (pass '-' for stdin)])
 # ARG_OPTIONAL_SINGLE([output],[o],[Name of the output file (pass '-' for stdout)],[-])
+# ARG_OPTIONAL_SINGLE([type],[t],[Output type to generate],[script])
 # ARG_OPTIONAL_BOOLEAN([library],[],[Whether the input file if the pure parsing library.])
 # ARG_OPTIONAL_BOOLEAN([check-typos],[],[Whether to check for possible argbash macro typos],[on])
 # ARG_OPTIONAL_BOOLEAN([commented],[c],[Commented mode - include explanatory comments with the parsing code],[off])
 # ARG_OPTIONAL_REPEATED([search],[I],[Directories to search for the wrapped scripts (directory of the template will be added to the end of the list)],["."])
 # ARG_OPTIONAL_SINGLE([debug],[],[(developer option) Tell autom4te to trace a macro])
+# ARG_TYPE_GROUP_SET([type],[],[type],[script,man])
 # ARG_DEFAULTS_POS([])
 # ARG_VERSION([echo "argbash v$version"])
 # ARG_HELP([Argbash is an argument parser generator for Bash.])
@@ -36,18 +38,30 @@ die()
 begins_with_short_option()
 {
 	local first_option all_short_options
-	all_short_options='ocIvh'
+	all_short_options='otcIvh'
 	first_option="${1:0:1}"
 	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
 
 
+# validators
+type()
+{
+	local _allowed=("script" "man")
+	local _seeking="$1"
+	for element in "${_allowed[@]}"
+	do
+		test "$element" = "$_seeking" && echo "$element" && return 0
+	done
+	die "Value '$_seeking' (of argument '$2') doesn't match the list of allowed values: 'script' and 'man'" 4
+}
 
 # THE DEFAULTS INITIALIZATION - POSITIONALS
 _positionals=()
 _arg_input=
 # THE DEFAULTS INITIALIZATION - OPTIONALS
 _arg_output="-"
+_arg_type="script"
 _arg_library="off"
 _arg_check_typos="on"
 _arg_commented="off"
@@ -57,9 +71,10 @@ _arg_debug=
 print_help ()
 {
 	printf '%s\n' "Argbash is an argument parser generator for Bash."
-	printf 'Usage: %s [-o|--output <arg>] [--(no-)library] [--(no-)check-typos] [-c|--(no-)commented] [-I|--search <arg>] [--debug <arg>] [-v|--version] [-h|--help] <input>\n' "$0"
+	printf 'Usage: %s [-o|--output <arg>] [-t|--type <>] [--(no-)library] [--(no-)check-typos] [-c|--(no-)commented] [-I|--search <arg>] [--debug <arg>] [-v|--version] [-h|--help] <input>\n' "$0"
 	printf '\t%s\n' "<input>: The input template file (pass '-' for stdin)"
 	printf '\t%s\n' "-o,--output: Name of the output file (pass '-' for stdout) (default: '-')"
+	printf '\t%s\n' "-t,--type: Output type to generate (one of 'script' and 'man'; default: 'script')"
 	printf '\t%s\n' "--library,--no-library: Whether the input file if the pure parsing library. (off by default)"
 	printf '\t%s\n' "--check-typos,--no-check-typos: Whether to check for possible argbash macro typos (on by default)"
 	printf '\t%s\n' "-c,--commented,--no-commented: Commented mode - include explanatory comments with the parsing code (off by default)"
@@ -85,6 +100,17 @@ parse_commandline ()
 				;;
 			-o*)
 				_arg_output="${_key##-o}"
+				;;
+			-t|--type)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_type="$(type "$2" "type")" || exit 1
+				shift
+				;;
+			--type=*)
+				_arg_type="$(type "${_key##--type=}" "type")" || exit 1
+				;;
+			-t*)
+				_arg_type="$(type "${_key##-t}" "type")" || exit 1
 				;;
 			--no-library|--library)
 				_arg_library="on"
@@ -173,6 +199,8 @@ assign_positional_args
 
 # OTHER STUFF GENERATED BY Argbash
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || die "Couldn't determine the script's running directory, which probably matters, bailing out" 2
+# Validation of values
+
 
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
@@ -231,6 +259,7 @@ do_stuff ()
 {
 	local _pass_also="$_wrapped_defns" input prefix_len _ret
 	test "$_arg_commented" = on && _pass_also="${_pass_also}m4_define([COMMENT_OUTPUT])"
+	_pass_also="${_pass_also}m4_define([_OUTPUT_TYPE], [[$1]])"
 	input="$(printf '%s\n' "$_pass_also" | cat - "$m4dir/argbash-lib.m4" "$output_m4")"
 	prefix_len=$(printf '%s\n' "$input" | wc -l)
 	input="$(printf '%s\n' "$input" | cat - "$infile")"
@@ -347,13 +376,13 @@ test "$_arg_library" = off && test -n "$parsing_code" && ($0 --library "$parsing
 # We may use some of the wrapping stuff, so let's fill the _wrapped_defns
 settle_wrapped_fname
 
-output="$(do_stuff)" || die "" "$?"
+output="$(do_stuff "$_arg_type")" || die "" "$?"
 if test "$_arg_check_typos" = on
 then
 	# match against suspicious, then inverse match against correct stuff:
 	# #<optional whitespace>\(allowed\|another allowed\|...\)<optional whitespace><opening bracket <or> end of line>
 	# Then, extract all matches (assumed to be alnum chars + '_') from grep and put them in the error msg.
-	grep_output="$(printf "%s" "$output" | grep '^#\s*\(ARG_\|ARGBASH\)' | grep -v '^#\s*\(ARGBASH_SET_INDENT\|ARG_POSITIONAL_SINGLE\|ARG_POSITIONAL_INF\|ARG_POSITIONAL_MULTI\|ARG_OPTIONAL_SINGLE\|ARG_POSITIONAL_DOUBLEDASH\|ARG_VERSION\|ARG_HELP\|INCLUDE_PARSING_CODE\|DEFINE_SCRIPT_DIR\|ARG_OPTIONAL_INCREMENTAL\|ARG_OPTIONAL_REPEATED\|ARG_VERBOSE\|ARG_OPTIONAL_BOOLEAN\|ARG_OPTIONAL_ACTION\|ARGBASH_SET_DELIM\|ARGBASH_GO\|ARGBASH_PREPARE\|ARGBASH_WRAP\|ARG_LEFTOVERS\|ARG_DEFAULTS_POS\|ARG_RESTRICT_VALUES\|ARG_OPTION_STACKING\|ARG_TYPE_GROUP\|ARG_TYPE_GROUP_SET\|ARG_USE_ENV\|ARG_USE_PROG\)\s*\((\|$\)' | sed -e 's/#\s*\([[:alnum:]_]*\).*/\1 /' | tr -d '\n\r')"
+	grep_output="$(printf "%s" "$output" | grep '^#\s*\(ARG_\|ARGBASH\)' | grep -v '^#\s*\(ARGBASH_SET_INDENT\|ARG_OPTIONAL_SINGLE\|ARG_VERSION\|ARG_HELP\|ARG_OPTIONAL_INCREMENTAL\|ARG_OPTIONAL_REPEATED\|ARG_VERBOSE\|ARG_OPTIONAL_BOOLEAN\|ARG_OPTIONAL_ACTION\|ARG_POSITIONAL_SINGLE\|ARG_POSITIONAL_INF\|ARG_POSITIONAL_MULTI\|ARG_POSITIONAL_DOUBLEDASH\|ARG_OPTION_STACKING\|ARG_RESTRICT_VALUES\|ARG_DEFAULTS_POS\|ARG_LEFTOVERS\|ARGBASH_WRAP\|INCLUDE_PARSING_CODE\|DEFINE_SCRIPT_DIR\|ARGBASH_SET_DELIM\|ARGBASH_GO\|ARGBASH_PREPARE\|ARG_TYPE_GROUP\|ARG_TYPE_GROUP_SET\|ARG_USE_ENV\|ARG_USE_PROG\)\s*\((\|$\)' | sed -e 's/#\s*\([[:alnum:]_]*\).*/\1 /' | tr -d '\n\r')"
 	test -n "$grep_output" && die "Your script contains possible misspelled Argbash macros: $grep_output" 1
 fi
 if test "$outfname" != '-'
