Implemented getopt feature parity

diff --git a/bin/argbash b/bin/argbash
--- a/bin/argbash
+++ b/bin/argbash
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-version=2.3.0
+version=2.4.0a
 # DEFINE_SCRIPT_DIR()
 # ARG_POSITIONAL_SINGLE([input],[The input template file (pass '-' for stdout)])
 # ARG_OPTIONAL_SINGLE([output],[o],[Name of the output file (pass '-' for stdout)],[-])
@@ -14,7 +14,7 @@ version=2.3.0
 
 # ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
-### START OF CODE GENERATED BY Argbash v2.3.0 one line above ###
+### START OF CODE GENERATED BY Argbash v2.4.0a one line above ###
 # Argbash is a bash code generator used to get arguments parsing right.
 # Argbash is FREE SOFTWARE, see https://argbash.io for more info
 
@@ -26,6 +26,16 @@ die()
 	echo "$1" >&2
 	exit ${_ret}
 }
+
+begins_with_short_option()
+{
+	local first_option all_short_options
+	all_short_options='ocIvh'
+	first_option="${1:0:1}"
+	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
+}
+
+
 
 # THE DEFAULTS INITIALIZATION - POSITIONALS
 _positionals=()
@@ -84,7 +94,10 @@ do
 		-c*|--no-commented|--commented)
 			_arg_commented="on"
 			_next="${_key##-c}"
-			test -n "$_next" && test "$_next" != "$_key" && shift && set -- "-c" "-${_next}" "$@"
+			if test -n "$_next" -a "$_next" != "$_key"
+			then
+				begins_with_short_option "$_next" && shift && set -- "-c" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+			fi
 			test "${1:0:5}" = "--no-" && _arg_commented="off"
 			;;
 		-I*|--search|--search=*)
diff --git a/bin/argbash-init b/bin/argbash-init
--- a/bin/argbash-init
+++ b/bin/argbash-init
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-version=2.3.0
+version=2.4.0a
 # ARG_POSITIONAL_SINGLE([output],[Name of the output template],["-"])
 # ARG_OPTIONAL_INCREMENTAL([separate],[s],[Separate the parsing logic (specify two times for complete separation)])
 # ARG_OPTIONAL_BOOLEAN([hints],[],[Whether to write hints to the script template])
@@ -15,7 +15,7 @@ version=2.3.0
 
 # ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
-### START OF CODE GENERATED BY Argbash v2.3.0 one line above ###
+### START OF CODE GENERATED BY Argbash v2.4.0a one line above ###
 # Argbash is a bash code generator used to get arguments parsing right.
 # Argbash is FREE SOFTWARE, see https://argbash.io for more info
 
@@ -27,6 +27,16 @@ die()
 	echo "$1" >&2
 	exit ${_ret}
 }
+
+begins_with_short_option()
+{
+	local first_option all_short_options
+	all_short_options='smvh'
+	first_option="${1:0:1}"
+	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
+}
+
+
 # validators
 mode()
 {
@@ -75,7 +85,10 @@ do
 		-s*|--separate)
 			_arg_separate=$((_arg_separate + 1))
 			_next="${_key##-s}"
-			test -n "$_next" && test "$_next" != "$_key" && shift && set -- "-s" "-${_next}" "$@"
+			if test -n "$_next" -a "$_next" != "$_key"
+			then
+				begins_with_short_option "$_next" && shift && set -- "-s" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+			fi
 			;;
 		--no-hints|--hints)
 			_arg_hints="on"
