Fixed indentation of generated bash functions.

diff --git a/bin/argbash b/bin/argbash
--- a/bin/argbash
+++ b/bin/argbash
@@ -67,85 +67,85 @@ parse_commandline ()
 	while test $# -gt 0
 	do
 		_key="$1"
-	case "$_key" in
-		-o|--output)
-			test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-			_val="$2"
-			shift
-			_arg_output="$_val"
-			;;
-		--output=*)
-			_val="${_key##--output=}"
-			_arg_output="$_val"
-			;;
-		-o*)
-			_val="${_key##-o}"
-			_arg_output="$_val"
-			;;
-		--no-library|--library)
-			_arg_library="on"
-			test "${1:0:5}" = "--no-" && _arg_library="off"
-			;;
-		--no-check-typos|--check-typos)
-			_arg_check_typos="on"
-			test "${1:0:5}" = "--no-" && _arg_check_typos="off"
-			;;
-		-c|--no-commented|--commented)
-			_arg_commented="on"
-			test "${1:0:5}" = "--no-" && _arg_commented="off"
-			;;
-		-c*)
-			_arg_commented="on"
-			_next="${_key##-c}"
-			if test -n "$_next" -a "$_next" != "$_key"
-			then
-				begins_with_short_option "$_next" && shift && set -- "-c" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
-			fi
-			;;
-		-I|--search)
-			test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-			_val="$2"
-			shift
-			_arg_search+=("$_val")
-			;;
-		--search=*)
-			_val="${_key##--search=}"
-			_arg_search+=("$_val")
-			;;
-		-I*)
-			_val="${_key##-I}"
-			_arg_search+=("$_val")
-			;;
-		--debug)
-			test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-			_val="$2"
-			shift
-			_arg_debug="$_val"
-			;;
-		--debug=*)
-			_val="${_key##--debug=}"
-			_arg_debug="$_val"
-			;;
-		-v|--version)
-			echo "argbash v$version"
-			exit 0
-			;;
-		-v*)
-			echo "argbash v$version"
-			exit 0
-			;;
-		-h|--help)
-			print_help
-			exit 0
-			;;
-		-h*)
-			print_help
-			exit 0
-			;;
-		*)
-			_positionals+=("$1")
-			;;
-	esac
+		case "$_key" in
+			-o|--output)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_val="$2"
+				shift
+				_arg_output="$_val"
+				;;
+			--output=*)
+				_val="${_key##--output=}"
+				_arg_output="$_val"
+				;;
+			-o*)
+				_val="${_key##-o}"
+				_arg_output="$_val"
+				;;
+			--no-library|--library)
+				_arg_library="on"
+				test "${1:0:5}" = "--no-" && _arg_library="off"
+				;;
+			--no-check-typos|--check-typos)
+				_arg_check_typos="on"
+				test "${1:0:5}" = "--no-" && _arg_check_typos="off"
+				;;
+			-c|--no-commented|--commented)
+				_arg_commented="on"
+				test "${1:0:5}" = "--no-" && _arg_commented="off"
+				;;
+			-c*)
+				_arg_commented="on"
+				_next="${_key##-c}"
+				if test -n "$_next" -a "$_next" != "$_key"
+				then
+					begins_with_short_option "$_next" && shift && set -- "-c" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+				fi
+				;;
+			-I|--search)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_val="$2"
+				shift
+				_arg_search+=("$_val")
+				;;
+			--search=*)
+				_val="${_key##--search=}"
+				_arg_search+=("$_val")
+				;;
+			-I*)
+				_val="${_key##-I}"
+				_arg_search+=("$_val")
+				;;
+			--debug)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_val="$2"
+				shift
+				_arg_debug="$_val"
+				;;
+			--debug=*)
+				_val="${_key##--debug=}"
+				_arg_debug="$_val"
+				;;
+			-v|--version)
+				echo "argbash v$version"
+				exit 0
+				;;
+			-v*)
+				echo "argbash v$version"
+				exit 0
+				;;
+			-h|--help)
+				print_help
+				exit 0
+				;;
+			-h*)
+				print_help
+				exit 0
+				;;
+			*)
+				_positionals+=("$1")
+				;;
+		esac
 		shift
 	done
 }
diff --git a/bin/argbash-init b/bin/argbash-init
--- a/bin/argbash-init
+++ b/bin/argbash-init
@@ -82,96 +82,96 @@ parse_commandline ()
 	while test $# -gt 0
 	do
 		_key="$1"
-	case "$_key" in
-		-s|--separate)
-			_arg_separate=$((_arg_separate + 1))
-			;;
-		-s*)
-			_arg_separate=$((_arg_separate + 1))
-			_next="${_key##-s}"
-			if test -n "$_next" -a "$_next" != "$_key"
-			then
-				begins_with_short_option "$_next" && shift && set -- "-s" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
-			fi
-			;;
-		--no-hints|--hints)
-			_arg_hints="on"
-			test "${1:0:5}" = "--no-" && _arg_hints="off"
-			;;
-		--pos)
-			test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-			_val="$2"
-			shift
-			_arg_pos+=("$_val")
-			;;
-		--pos=*)
-			_val="${_key##--pos=}"
-			_arg_pos+=("$_val")
-			;;
-		--opt)
-			test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-			_val="$2"
-			shift
-			_arg_opt+=("$_val")
-			;;
-		--opt=*)
-			_val="${_key##--opt=}"
-			_arg_opt+=("$_val")
-			;;
-		--opt-bool)
-			test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-			_val="$2"
-			shift
-			_arg_opt_bool+=("$_val")
-			;;
-		--opt-bool=*)
-			_val="${_key##--opt-bool=}"
-			_arg_opt_bool+=("$_val")
-			;;
-		--wrap)
-			test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-			_val="$2"
-			shift
-			_arg_wrap+=("$_val")
-			;;
-		--wrap=*)
-			_val="${_key##--wrap=}"
-			_arg_wrap+=("$_val")
-			;;
-		-m|--mode)
-			test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-			_val="$2"
-			shift
-			_arg_mode="$_val"
-			;;
-		--mode=*)
-			_val="${_key##--mode=}"
-			_arg_mode="$_val"
-			;;
-		-m*)
-			_val="${_key##-m}"
-			_arg_mode="$_val"
-			;;
-		-v|--version)
-			echo "argbash-init v$version"
-			exit 0
-			;;
-		-v*)
-			echo "argbash-init v$version"
-			exit 0
-			;;
-		-h|--help)
-			print_help
-			exit 0
-			;;
-		-h*)
-			print_help
-			exit 0
-			;;
-		*)
-			_positionals+=("$1")
-			;;
-	esac
+		case "$_key" in
+			-s|--separate)
+				_arg_separate=$((_arg_separate + 1))
+				;;
+			-s*)
+				_arg_separate=$((_arg_separate + 1))
+				_next="${_key##-s}"
+				if test -n "$_next" -a "$_next" != "$_key"
+				then
+					begins_with_short_option "$_next" && shift && set -- "-s" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+				fi
+				;;
+			--no-hints|--hints)
+				_arg_hints="on"
+				test "${1:0:5}" = "--no-" && _arg_hints="off"
+				;;
+			--pos)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_val="$2"
+				shift
+				_arg_pos+=("$_val")
+				;;
+			--pos=*)
+				_val="${_key##--pos=}"
+				_arg_pos+=("$_val")
+				;;
+			--opt)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_val="$2"
+				shift
+				_arg_opt+=("$_val")
+				;;
+			--opt=*)
+				_val="${_key##--opt=}"
+				_arg_opt+=("$_val")
+				;;
+			--opt-bool)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_val="$2"
+				shift
+				_arg_opt_bool+=("$_val")
+				;;
+			--opt-bool=*)
+				_val="${_key##--opt-bool=}"
+				_arg_opt_bool+=("$_val")
+				;;
+			--wrap)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_val="$2"
+				shift
+				_arg_wrap+=("$_val")
+				;;
+			--wrap=*)
+				_val="${_key##--wrap=}"
+				_arg_wrap+=("$_val")
+				;;
+			-m|--mode)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_val="$2"
+				shift
+				_arg_mode="$_val"
+				;;
+			--mode=*)
+				_val="${_key##--mode=}"
+				_arg_mode="$_val"
+				;;
+			-m*)
+				_val="${_key##-m}"
+				_arg_mode="$_val"
+				;;
+			-v|--version)
+				echo "argbash-init v$version"
+				exit 0
+				;;
+			-v*)
+				echo "argbash-init v$version"
+				exit 0
+				;;
+			-h|--help)
+				print_help
+				exit 0
+				;;
+			-h*)
+				print_help
+				exit 0
+				;;
+			*)
+				_positionals+=("$1")
+				;;
+		esac
 		shift
 	done
 }
