Fixed some bugs, updated docs.

diff --git a/bin/argbash b/bin/argbash
--- a/bin/argbash
+++ b/bin/argbash
@@ -16,23 +16,32 @@ version=2.0.0
 # Argbash is a bash code generator used to get arguments parsing right.
 # Argbash is FREE SOFTWARE, know your rights: https://github.com/matejak/argbash
 
+die()
+{
+	local _ret=$2
+	test -n "$_ret" || _ret=1
+	test "$_PRINT_HELP" = yes && print_help >&2
+	echo "$1" >&2
+	exit ${_ret}
+}
+
 # THE DEFAULTS INITIALIZATION --- POSITIONALS
 # THE DEFAULTS INITIALIZATION --- OPTIONALS
 _arg_output="-"
 _arg_standalone=off
 _arg_search=(".")
-_arg_debug=""
+_arg_debug=
 
 # THE PRINT HELP FUNCION
 print_help ()
 {
 	echo "Argbash is an argument parser generator for Bash."
 	printf 'Usage: %s [-o|--output <arg>] [--(no-)standalone] [-I|--search] [--debug <arg>] [-v|--version] [-h|--help] <input>\n' "$0"
-	printf "\t<input>: The input template file\n"
+	printf "\t<input->: The input template file\n"
 	printf "\t-o,--output: Name of the output file (pass '-' for stdout) (default: '%s')\n" "${_arg_output}"
 	printf "\t--standalone,--no-standalone: Whether the parsing code is in a standalone file. (%s by default)\n" "${_arg_standalone}"
 	printf "\t-I,--search: Directories to search for the wrapped scripts (directory of the template will be added to the end of the list) (default array: (%s) )\n" "${_arg_search[*]}"
-	printf "\t--debug: (developer option) Tell autom4te to trace a macro (default: '%s')\n" "${_arg_debug}"
+	printf "\t--debug: (developer option) Tell autom4te to trace a macro (no default)\n"
 	printf "\t-v,--version: Prints version\n"
 	printf "\t-h,--help: Prints help\n"
 }
@@ -43,7 +52,7 @@ do
 	_key="$1"
 	case "$_key" in
 		-o|--output)
-			test $# -lt 2 && { echo "Missing value for the optional argument '$_key'." >&2; exit 1; }
+			test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
 			_arg_output="$2"
 
 			shift
@@ -54,13 +63,13 @@ do
 			test "${1:0:5}" = "--no-" && _arg_standalone="off"
 			;;
 		-I|--search)
-			test $# -lt 2 && { echo "Missing value for the optional argument '$_key'." >&2; exit 1; }
+			test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
 			_arg_search+=("$2")
 
 			shift
 			;;
 		--debug)
-			test $# -lt 2 && { echo "Missing value for the optional argument '$_key'." >&2; exit 1; }
+			test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
 			_arg_debug="$2"
 
 			shift
@@ -76,20 +85,21 @@ do
 		*)
 			_positionals+=("$1")
 			;;
+
 	esac
 	shift
 done
 
 _positional_names=('_arg_input' )
-test ${#_positionals[@]} -lt 1 && { ( echo "FATAL ERROR: Not enough positional arguments --- we require exactly 1, but got only ${#_positionals[@]}."; print_help ) >&2; exit 1; }
-test ${#_positionals[@]} -gt 1 && { ( echo "FATAL ERROR: There were spurious positional arguments --- we expect exactly 1, but got ${#_positionals[@]} (the last one was: '${_positionals[*]: -1}')."; print_help ) >&2; exit 1; }
+test ${#_positionals[@]} -lt 1 && _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 1, but got only ${#_positionals[@]}." 1
+test ${#_positionals[@]} -gt 1 && _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 1, but got ${#_positionals[@]} (the last one was: '${_positionals[*]: -1}')." 1
 for (( ii = 0; ii < ${#_positionals[@]}; ii++))
 do
-	eval "${_positional_names[ii]}=\${_positionals[ii]}" || { echo "Error during argument parsing, possibly an Argbash bug." >&2; exit 1; }
+	eval "${_positional_names[ii]}=\${_positionals[ii]}" || die "Error during argument parsing, possibly an Argbash bug." 1
 done
 
 # OTHER STUFF GENERATED BY Argbash
-script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || { echo "Couldn't determine the script's running directory, which probably matters, bailing out" >&2; exit 2; }
+script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || die "Couldn't determine the script's running directory, which probably matters, bailing out" 2
 
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
@@ -120,7 +130,7 @@ settle_wrapped_fname ()
 	IFS=$'\n' _srcfiles=($(echo 'm4_changecom()m4_define([ARGBASH_WRAP])' "$(cat "$infile")" \
 			| autom4te -l m4sugar -t 'ARGBASH_WRAP:$1'))
 
-	test -n "$_srcfiles" || return
+	test "${#_srcfiles[@]}" -gt 0 || return
 	for srcstem in "${_srcfiles[@]}"
 	do
 		_found=no
diff --git a/bin/argbash-1to2 b/bin/argbash-1to2
--- a/bin/argbash-1to2
+++ b/bin/argbash-1to2
@@ -1,9 +1,9 @@
 #!/bin/bash
 
 version=2.0.0
-# DEFINE_SCRIPT_DIR()
 # ARG_POSITIONAL_INF([input],[The input file to transform],[1])
 # ARG_OPTIONAL_SINGLE([output],[o],[Name of the output file (pass '-' for stdout and empty string for the same as input file)],[""])
+# ARG_VERSION([echo "argbash-1to2 v$version"])
 # ARG_HELP([Convert a template for argbash<2 to argbash>=2,<3])
 
 # ARGBASH_GO()
@@ -11,6 +11,15 @@ version=2.0.0
 ### START OF CODE GENERATED BY Argbash v2.0.0 one line above ###
 # Argbash is a bash code generator used to get arguments parsing right.
 # Argbash is FREE SOFTWARE, know your rights: https://github.com/matejak/argbash
+
+die()
+{
+	local _ret=$2
+	test -n "$_ret" || _ret=1
+	test "$_PRINT_HELP" = yes && print_help >&2
+	echo "$1" >&2
+	exit ${_ret}
+}
 
 # THE DEFAULTS INITIALIZATION --- POSITIONALS
 _arg_input=('' )
@@ -21,9 +30,10 @@ _arg_output=""
 print_help ()
 {
 	echo "Convert a template for argbash<2 to argbash>=2<3"
-	printf 'Usage: %s [-o|--output <arg>] [-h|--help] <input-1> [<input-2>] ... [<input-n>] ...\n' "$0"
-	printf "\t<input>: The input file to transform\n"
+	printf 'Usage: %s [-o|--output <arg>] [-v|--version] [-h|--help] <input-1> [<input-2>] ... [<input-n>] ...\n' "$0"
+	printf "\t<input->: The input file to transform\n"
 	printf "\t-o,--output: Name of the output file (pass '-' for stdout and empty string for the same as input file) (default: '%s')\n" "${_arg_output}"
+	printf "\t-v,--version: Prints version\n"
 	printf "\t-h,--help: Prints help\n"
 }
 
@@ -33,10 +43,14 @@ do
 	_key="$1"
 	case "$_key" in
 		-o|--output)
-			test $# -lt 2 && { echo "Missing value for the optional argument '$_key'." >&2; exit 1; }
+			test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
 			_arg_output="$2"
 
 			shift
+			;;
+		-v|--version)
+			echo "argbash-1to2 v$version"
+			exit 0
 			;;
 		-h|--help)
 			print_help
@@ -45,25 +59,25 @@ do
 		*)
 			_positionals+=("$1")
 			;;
+
 	esac
 	shift
 done
 
 _positional_names=('_arg_input' )
-test ${#_positionals[@]} -lt 1 && { ( echo "FATAL ERROR: Not enough positional arguments --- we require at least 1, but got only ${#_positionals[@]}."; print_help ) >&2; exit 1; }
+test ${#_positionals[@]} -lt 1 && _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1, but got only ${#_positionals[@]}." 1
 _OUR_ARGS=$((${#_positionals[@]} - ${#_positional_names[@]}))
-for (( ii = 0; ii < $_OUR_ARGS; ii++))
+for (( ii = 0; ii < _OUR_ARGS; ii++))
 do
 	_positional_names+=("_arg_input[(($ii + 1))]")
 done
 
 for (( ii = 0; ii < ${#_positionals[@]}; ii++))
 do
-	eval "${_positional_names[ii]}=\${_positionals[ii]}" || { echo "Error during argument parsing, possibly an Argbash bug." >&2; exit 1; }
+	eval "${_positional_names[ii]}=\${_positionals[ii]}" || die "Error during argument parsing, possibly an Argbash bug." 1
 done
 
 # OTHER STUFF GENERATED BY Argbash
-script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || { echo "Couldn't determine the script's running directory, which probably matters, bailing out" >&2; exit 2; }
 
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
@@ -80,6 +94,8 @@ do_stuff ()
 }
 
 outfname="$_arg_output"
+test "${#infname[@]}" -gt 1 && test -n "$outfname" && die "You have specified more than one (${#infname[@]}) input filenames, so you probably want to modify the corresponding files in-place. In order to do so, you can't specify an output filename, even '-' does make no sense (currently: '$outfname')"
+
 for infname in "${_arg_input[@]}"
 do
 	test -f "$infname" || { echo "The input parameter has to be a file (got: '$infname')" >&2; exit 1; }
@@ -95,7 +111,8 @@ do
 		trap "rm -f $temp_outfile" EXIT
 		do_stuff > "$temp_outfile"
 		mv "$temp_outfile" "$outfname"
-		chmod a+x "$outfname"
+		# So we don't make .m4 scripts executable
+		chmod --reference "$infname" "$outfname"
 	fi
 done
 
