Better shellcheck support
Supports --enable=all for optional checks
Adds shellcheck directives to properly source files

diff --git a/bin/argbash-1to2 b/bin/argbash-1to2
--- a/bin/argbash-1to2
+++ b/bin/argbash-1to2
@@ -6,7 +6,7 @@
 version=2.10.0
 # ARG_POSITIONAL_INF([input],[The input file to transform],[1])
 # ARG_OPTIONAL_SINGLE([output],[o],[Name of the output file (pass '-' for stdout and empty string for the same as input file)],[""])
-# ARG_VERSION([echo "argbash-1to2 v$version"])
+# ARG_VERSION([echo "argbash-1to2 v${version}"])
 # ARG_HELP([Convert a template for argbash>=1,<2 to argbash>=2,<3])
 
 # ARGBASH_GO()
@@ -29,7 +29,7 @@ begins_with_short_option()
 {
 	local first_option all_short_options='ovh'
 	first_option="${1:0:1}"
-	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
+	test "${all_short_options}" = "${all_short_options/${first_option}/}" && return 1 || return 0
 }
 
 # THE DEFAULTS INITIALIZATION - POSITIONALS
@@ -56,9 +56,9 @@ parse_commandline()
 	while test $# -gt 0
 	do
 		_key="$1"
-		case "$_key" in
+		case "${_key}" in
 			-o|--output)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				test $# -lt 2 && die "Missing value for the optional argument '${_key}'." 1
 				_arg_output="$2"
 				shift
 				;;
@@ -69,11 +69,11 @@ parse_commandline()
 				_arg_output="${_key##-o}"
 				;;
 			-v|--version)
-				echo "argbash-1to2 v$version"
+				echo "argbash-1to2 v${version}"
 				exit 0
 				;;
 			-v*)
-				echo "argbash-1to2 v$version"
+				echo "argbash-1to2 v${version}"
 				exit 0
 				;;
 			-h|--help)
@@ -86,7 +86,7 @@ parse_commandline()
 				;;
 			*)
 				_last_positional="$1"
-				_positionals+=("$_last_positional")
+				_positionals+=("${_last_positional}")
 				_positionals_count=$((_positionals_count + 1))
 				;;
 		esac
@@ -98,7 +98,7 @@ parse_commandline()
 handle_passed_args_count()
 {
 	local _required_args_string="'input'"
-	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: ${_required_args_string}), but got only ${_positionals_count}." 1
 }
 
 
@@ -109,14 +109,14 @@ assign_positional_args()
 	_our_args=$((${#_positionals[@]} - 1))
 	for ((ii = 0; ii < _our_args; ii++))
 	do
-		_positional_names="$_positional_names _arg_input[$((ii + 1))]"
+		_positional_names="${_positional_names} _arg_input[$((ii + 1))]"
 	done
 
-	shift "$_shift_for"
+	shift "${_shift_for}"
 	for _positional_name in ${_positional_names}
 	do
 		test $# -gt 0 || break
-		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
+		eval "${_positional_name}=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
 		shift
 	done
 }
@@ -138,36 +138,37 @@ cleanup()
 	test "${#_files_to_clean[*]}" != 0 && rm -f "${_files_to_clean[@]}"
 }
 
-do_stuff ()
+do_stuff()
 {
 	# SCRIPT_DIR is likely also a default, but maybe not - it may have been set explicitly
-	grep -q '\${\?SCRIPT_DIR' -- "$infname" && echo "You probably use a variable 'SCRIPT_DIR' in your script. It may be that you should rename it to 'script_dir', but this is not certain :-(" >&2
+	grep -q '\${\?SCRIPT_DIR' -- "${infname}" && echo "You probably use a variable 'SCRIPT_DIR' in your script. It may be that you should rename it to 'script_dir', but this is not certain :-(" >&2
 	# We match $_ARG_FOO as well as ${ARG_FOO...
 	# and _ARGS_FOO
-	sed 's/\(\${\?_ARGS\?_\w\+\)/\L\1\l/g' "$infname"
+	sed 's/\(\${\?_ARGS\?_\w\+\)/\L\1\l/g' "${infname}"
 }
 
-outfname="$_arg_output"
-test "${#infname[@]}" -gt 1 && test -n "$outfname" && die "You have specified more than one (${#infname[@]}) input filenames, so you probably want to modify the corresponding files in-place. In order to do so, you can't specify an output filename, even '-' does make no sense (currently: '$outfname')"
+outfname="${_arg_output}"
+test "${#infname[@]}" -gt 1 && test -n "${outfname}" && die "You have specified more than one (${#infname[@]}) input filenames, so you probably want to modify the corresponding files in-place. In order to do so, you can't specify an output filename, even '-' does make no sense (currently: '${outfname}')"
 
 trap cleanup EXIT
-for infname in "${_arg_input[@]}"
-do
-	test -f "$infname" || { echo "The input parameter has to be a file (got: '$infname')" >&2; exit 1; }
+for infname in "${_arg_input[@]}"; do
+	test -f "${infname}" || {
+		echo "The input parameter has to be a file (got: '${infname}')" >&2
+		exit 1
+	}
 
-	test -n "$_arg_output" || outfname="$infname"
-	if test "$outfname" = '-'
-	then
+	test -n "${_arg_output}" || outfname="${infname}"
+	if test "${outfname}" = '-'; then
 		do_stuff
 	else
 		# vvv This should catch most of the cases when we want to overwrite the source file
 		# vvv and we don't want to leave a file (not even an empty one) when something goes wrong.
 		temp_outfile="temp_$$"
-		_files_to_clean+=("$temp_outfile")
-		do_stuff > "$temp_outfile"
-		mv "$temp_outfile" "$outfname"
+		_files_to_clean+=("${temp_outfile}")
+		do_stuff > "${temp_outfile}"
+		mv "${temp_outfile}" "${outfname}"
 		# So we don't make .m4 scripts executable
-		chmod --reference "$infname" "$outfname"
+		chmod --reference "${infname}" "${outfname}"
 	fi
 done
 
diff --git a/bin/argbash-init b/bin/argbash-init
--- a/bin/argbash-init
+++ b/bin/argbash-init
@@ -14,7 +14,7 @@ version=2.10.0
 # ARG_OPTIONAL_REPEATED([wrap],[],[What script(s) to wrap])
 # ARG_OPTIONAL_SINGLE([mode],[m],[The slider between feature-rich and simple script.],[default])
 # ARG_TYPE_GROUP_SET([mode],[MODE],[mode],[default,full,minimal])
-# ARG_VERSION([echo "argbash-init v$version"])
+# ARG_VERSION([echo "argbash-init v${version}"])
 # ARG_HELP([Make a template for scripts.])
 
 # ARGBASH_GO()
@@ -39,9 +39,9 @@ mode()
 	local _allowed=("default" "full" "minimal") _seeking="$1"
 	for element in "${_allowed[@]}"
 	do
-		test "$element" = "$_seeking" && echo "$element" && return 0
+		test "${element}" = "${_seeking}" && echo "${element}" && return 0
 	done
-	die "Value '$_seeking' (of argument '$2') doesn't match the list of allowed values: 'default', 'full' and 'minimal'" 4
+	die "Value '${_seeking}' (of argument '$2') doesn't match the list of allowed values: 'default', 'full' and 'minimal'" 4
 }
 
 
@@ -49,7 +49,7 @@ begins_with_short_option()
 {
 	local first_option all_short_options='smvh'
 	first_option="${1:0:1}"
-	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
+	test "${all_short_options}" = "${all_short_options/${first_option}/}" && return 1 || return 0
 }
 
 # THE DEFAULTS INITIALIZATION - POSITIONALS
@@ -88,16 +88,16 @@ parse_commandline()
 	while test $# -gt 0
 	do
 		_key="$1"
-		case "$_key" in
+		case "${_key}" in
 			-s|--separate)
 				_arg_separate=$((_arg_separate + 1))
 				;;
 			-s*)
 				_arg_separate=$((_arg_separate + 1))
 				_next="${_key##-s}"
-				if test -n "$_next" -a "$_next" != "$_key"
+				if test -n "${_next}" -a "${_next}" != "${_key}"
 				then
-					{ begins_with_short_option "$_next" && shift && set -- "-s" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+					{ begins_with_short_option "${_next}" && shift && set -- "-s" "-${_next}" "$@"; } || die "The short option '${_key}' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
 				fi
 				;;
 			--no-hints|--hints)
@@ -105,7 +105,7 @@ parse_commandline()
 				test "${1:0:5}" = "--no-" && _arg_hints="off"
 				;;
 			--pos)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				test $# -lt 2 && die "Missing value for the optional argument '${_key}'." 1
 				_arg_pos+=("$2")
 				shift
 				;;
@@ -113,7 +113,7 @@ parse_commandline()
 				_arg_pos+=("${_key##--pos=}")
 				;;
 			--opt)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				test $# -lt 2 && die "Missing value for the optional argument '${_key}'." 1
 				_arg_opt+=("$2")
 				shift
 				;;
@@ -121,7 +121,7 @@ parse_commandline()
 				_arg_opt+=("${_key##--opt=}")
 				;;
 			--opt-bool)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				test $# -lt 2 && die "Missing value for the optional argument '${_key}'." 1
 				_arg_opt_bool+=("$2")
 				shift
 				;;
@@ -129,7 +129,7 @@ parse_commandline()
 				_arg_opt_bool+=("${_key##--opt-bool=}")
 				;;
 			--wrap)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				test $# -lt 2 && die "Missing value for the optional argument '${_key}'." 1
 				_arg_wrap+=("$2")
 				shift
 				;;
@@ -137,7 +137,7 @@ parse_commandline()
 				_arg_wrap+=("${_key##--wrap=}")
 				;;
 			-m|--mode)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				test $# -lt 2 && die "Missing value for the optional argument '${_key}'." 1
 				_arg_mode="$(mode "$2" "mode")" || exit 1
 				shift
 				;;
@@ -148,11 +148,11 @@ parse_commandline()
 				_arg_mode="$(mode "${_key##-m}" "mode")" || exit 1
 				;;
 			-v|--version)
-				echo "argbash-init v$version"
+				echo "argbash-init v${version}"
 				exit 0
 				;;
 			-v*)
-				echo "argbash-init v$version"
+				echo "argbash-init v${version}"
 				exit 0
 				;;
 			-h|--help)
@@ -165,7 +165,7 @@ parse_commandline()
 				;;
 			*)
 				_last_positional="$1"
-				_positionals+=("$_last_positional")
+				_positionals+=("${_last_positional}")
 				_positionals_count=$((_positionals_count + 1))
 				;;
 		esac
@@ -185,11 +185,11 @@ assign_positional_args()
 	local _positional_name _shift_for=$1
 	_positional_names="_arg_output "
 
-	shift "$_shift_for"
+	shift "${_shift_for}"
 	for _positional_name in ${_positional_names}
 	do
 		test $# -gt 0 || break
-		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
+		eval "${_positional_name}=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
 		shift
 	done
 }
@@ -205,131 +205,108 @@ assign_positional_args 1 "${_positionals[@]}"
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
 
-
 _variables=()
 HAVE_POSITIONAL_ARG=no
 
-
-# This should be in sync with _translit_var in stuff.m4
-_translit_var()
+# This should be in sync with _translate_var in stuff.m4
+_translate_var()
 {
-	printf "\$_arg_%s" "$1" | tr '[:upper:]' '[:lower:]' | tr '-' '_'
+	printf '${_arg_%s}' "$1" | tr '[:upper:]' '[:lower:]' | tr '-' '_'
 }
-
 
 optional_argument_without_hints()
 {
 	echo "# ARG_OPTIONAL_SINGLE([$1])"
 }
 
-
 optional_argument_with_hints()
 {
 	echo "# ARG_OPTIONAL_SINGLE([$1], [<short option character (optional)>], [<help message (optional)>], [<default (optional)>])"
 }
 
-
 optional_argument()
 {
 	"${FUNCNAME[0]}_$2" "$1"
-	_variables+=("printf 'Value of --%s: %s\\n' '$1' \"$(_translit_var "$1")\"")
+	_variables+=("printf 'Value of --%s: %s\\n' '$1' \"$(_translate_var "$1")\"")
 }
-
 
 boolean_argument_with_hints()
 {
 	echo "# ARG_OPTIONAL_BOOLEAN([$1], [<short option character (optional)>], [<help message (optional)>], [<default (optional), off by default>])"
 }
 
-
 boolean_argument_without_hints()
 {
 	echo "# ARG_OPTIONAL_BOOLEAN([$1])"
 }
 
-
 boolean_argument()
 {
 	"${FUNCNAME[0]}_$2" "$1"
-	_variables+=("printf \"'%s' is %s\\\\n\" '$1' \"$(_translit_var "$1")\"")
+	_variables+=("printf \"'%s' is %s\\\\n\" '$1' \"$(_translate_var "$1")\"")
 }
-
 
 positional_argument_with_hints()
 {
 	echo "# ARG_POSITIONAL_SINGLE([$1], [<help message (optional)>], [<default (optional)])"
 }
 
-
 positional_argument_without_hints()
 {
 	echo "# ARG_POSITIONAL_SINGLE([$1])"
 }
 
-
 positional_argument()
 {
 	HAVE_POSITIONAL_ARG=yes
 	"${FUNCNAME[0]}_$2" "$1"
-	_variables+=("printf \"Value of '%s': %s\\\\n\" '$1' \"$(_translit_var "$1")\"")
+	_variables+=("printf \"Value of '%s': %s\\\\n\" '$1' \"$(_translate_var "$1")\"")
 }
-
 
 do_header()
 {
 	echo "#!/bin/bash"
 	echo
 	# We if separate == 2, we don't want to pass this to argbash at all
-	test "$_arg_separate" = 2 && test "$1" = "script" && echo "# Created by argbash-init v$version" && return
+	test "${_arg_separate}" = 2 && test "$1" = "script" && echo "# Created by argbash-init v${version}" && return
 	echo "# m4_ignore("
-	if test "$1" = "lib"
-	then
-		echo "echo \"This is just a parsing library template, not the library - pass the parent script '$outfname' to 'argbash' to fix this.\" >&2"
-	elif test "$1" = "standalone_lib"
-	then
+	if test "$1" = "lib"; then
+		echo "echo \"This is just a parsing library template, not the library - pass the parent script '${outfname}' to 'argbash' to fix this.\" >&2"
+	elif test "$1" = "standalone_lib"; then
 		echo "echo \"This is just a parsing library template, not the library - pass this file to 'argbash' to fix this.\" >&2"
 	else
 		echo "echo \"This is just a script template, not the script (yet) - pass it to 'argbash' to fix this.\" >&2"
 	fi
-	echo "exit 11  #)Created by argbash-init v$version"
+	echo "exit 11  #)Created by argbash-init v${version}"
 }
-
 
 do_args()
 {
 	local _mode="without_hints"
-	if test "$_arg_hints" = on
-	then
+	if test "${_arg_hints}" = on; then
 		echo "# Rearrange the order of options below according to what you would like to see in the help message."
 		_mode="with_hints"
 	fi
-	for name in "${_arg_opt[@]}"
-	do optional_argument "$name" "$_mode"; done
-	for name in "${_arg_opt_bool[@]}"
-	do boolean_argument "$name" "$_mode"; done
-	for name in "${_arg_pos[@]}"
-	do positional_argument "$name" "$_mode"; done
+	for name in "${_arg_opt[@]}"; do optional_argument "${name}" "${_mode}"; done
+	for name in "${_arg_opt_bool[@]}"; do boolean_argument "${name}" "${_mode}"; done
+	for name in "${_arg_pos[@]}"; do positional_argument "${name}" "${_mode}"; done
 }
-
 
 do_args_footer()
 {
-	if test "$_arg_mode" = "full"
-	then
+	if test "${_arg_mode}" = "full"; then
 		echo '# ARGBASH_SET_DELIM([ =])'
 		echo '# ARG_OPTION_STACKING([getopt])'
 		echo '# ARG_RESTRICT_VALUES([no-local-options])'
-	elif test "$_arg_mode" = "minimal"
-	then
+	elif test "${_arg_mode}" = "minimal"; then
 		echo '# ARGBASH_SET_DELIM([ ])'
 		echo '# ARG_OPTION_STACKING([none])'
 		echo '# ARG_RESTRICT_VALUES([none])'
 	fi
-	test "$HAVE_POSITIONAL_ARG" = yes && echo '# ARG_DEFAULTS_POS'
+	test "${HAVE_POSITIONAL_ARG}" = yes && echo '# ARG_DEFAULTS_POS'
 	echo "# ARG_HELP([<The general help message of my script>])"
 	echo "# ARGBASH_GO"
 }
-
 
 do_script_assisted()
 {
@@ -342,7 +319,6 @@ do_script_assisted()
 	do_body_protected
 }
 
-
 #
 # $1: The filename of the parsing library
 do_script_separate()
@@ -350,25 +326,23 @@ do_script_separate()
 	do_header script
 	parse_fname=${parse_fname_stem}.sh
 
-	echo "# Run 'argbash --strip user-content \"$1\" -o \"$parse_fname\"' to generate the '$parse_fname' file."
-	echo "# If you need to make changes later, edit '$parse_fname' directly, and regenerate by running"
-	echo "# 'argbash --strip user-content \"$parse_fname\" -o \"$parse_fname\"'"
+	echo "# Run 'argbash --strip user-content \"$1\" -o \"${parse_fname}\"' to generate the '${parse_fname}' file."
+	echo "# If you need to make changes later, edit '${parse_fname}' directly, and regenerate by running"
+	echo "# 'argbash --strip user-content \"${parse_fname}\" -o \"${parse_fname}\"'"
 	echo 'script_dir="$(cd "$(dirname "$(readlink -e "${BASH_SOURCE[0]}")")" && pwd)"'
-	echo '. "${script_dir}/'"$(basename "$parse_fname")\" || { echo \"Couldn't find '$(basename "$parse_fname")' parsing library in the '"'$script_dir'"' directory\"; exit 1; }"
+	echo '. "${script_dir}/'"$(basename "${parse_fname}")\" || { echo \"Couldn't find '$(basename "${parse_fname}")' parsing library in the '"'${script_dir}'"' directory\"; exit 1; }"
 	echo
 
 	do_body
 }
-
 
 do_body()
 {
 	echo "# vvv  PLACE YOUR CODE HERE  vvv"
 	if test "${#_variables[@]}" -gt 0; then
 		echo "# For example:"
-		for stat in "${_variables[@]}"
-		do
-			echo "$stat"
+		for stat in "${_variables[@]}"; do
+			echo "${stat}"
 		done
 		echo
 	else
@@ -378,7 +352,6 @@ do_body()
 	fi
 	echo "# ^^^  TERMINATE YOUR CODE BEFORE THE BOTTOM ARGBASH MARKER  ^^^"
 }
-
 
 do_body_protected()
 {
@@ -390,45 +363,41 @@ do_body_protected()
 	echo "# ] <-- needed because of Argbash"
 }
 
-
 do_stuff()
 {
 	do_header "$1"
 	do_args
 	do_args_footer
 
-	test "$_arg_separate" = 0 && do_body_protected
+	test "${_arg_separate}" = 0 && do_body_protected
 }
 
-outfname="$_arg_output"
+outfname="${_arg_output}"
 # we canonicize the empty string input to output filename to the dash
-test -n "$outfname" || outfname='-'
-test "$outfname" = "-" -a "$_arg_separate" -gt 0 && die "If you want to separate parsing and script body, you have to specify the outname, stdout doesn't work."
+test -n "${outfname}" || outfname='-'
+test "${outfname}" = "-" -a "${_arg_separate}" -gt 0 && die "If you want to separate parsing and script body, you have to specify the outname, stdout doesn't work."
 
-if test "$outfname" = '-'
-then
+if test "${outfname}" = '-'; then
 	do_stuff 'script'
 else
-	if test "$_arg_separate" = 0
-	then
-		do_stuff 'script' > "$outfname"
+	if test "${_arg_separate}" = 0; then
+		do_stuff 'script' > "${outfname}"
 	else
 		parse_fname_stem="$(echo "${outfname}" | sed -e 's/\.\(sh\|m4\)$//')-parsing"
 
 		# IMPORTANT NOTION:
 		# do_stuff has to be called FIRST, because it sets the _variables array content as its side-effect
-		if test "$_arg_separate" = 1
-		then
+		if test "${_arg_separate}" = 1; then
 			do_stuff 'lib' > "${parse_fname_stem}.m4"
-			do_script_assisted > "$outfname"
+			do_script_assisted > "${outfname}"
 		else
-			test "$_arg_separate" = 2 || echo "The greatest separation value is 2, got $_arg_separate" >&2
+			test "${_arg_separate}" = 2 || echo "The greatest separation value is 2, got ${_arg_separate}" >&2
 			parsing_library_file="${parse_fname_stem}.m4"
-			do_stuff 'standalone_lib'  > "${parsing_library_file}"
-			do_script_separate "$parsing_library_file" > "$outfname"
+			do_stuff 'standalone_lib' > "${parsing_library_file}"
+			do_script_separate "${parsing_library_file}" > "${outfname}"
 		fi
 	fi
-	chmod a+x "$outfname"
+	chmod a+x "${outfname}"
 fi
 
 #
diff --git a/tests/regressiontests/reverse b/tests/regressiontests/reverse
--- a/tests/regressiontests/reverse
+++ b/tests/regressiontests/reverse
@@ -1,27 +1,23 @@
 #!/bin/bash
 
-if test -n "$ERROR"
-then
+if test -n "${ERROR}"; then
 	ERRSTRING="$("$@" 2>&1)"
 else
 	"$@"
 fi
 
-if test $? = 0
-then
+if test $? = 0; then
 	echo "Error expected, but it did not occur" >&2
 	exit 1
 # We don't care what the error string should look like
-elif test -z "$ERROR"
-then
+elif test -z "${ERROR}"; then
 	exit 0
 # We examine the error string
 else
-	if echo "$ERRSTRING" | grep -q "$ERROR"
-	then
+	if echo "${ERRSTRING}" | grep -q "${ERROR}"; then
 		exit 0
 	else
-		echo "Error occured, but not a good one:" >&2
+		echo "Error occurred, but not the expected error:" >&2
 		"$@"
 	fi
 fi
