Implemented API change to 2.0 (small arg variable names)

diff --git a/bin/argbash b/bin/argbash
--- a/bin/argbash
+++ b/bin/argbash
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-version=1.4.2
+version=2.0.0
 # DEFINE_SCRIPT_DIR()
 # ARG_POSITIONAL_SINGLE([input],[The input template file])
 # ARG_OPTIONAL_SINGLE([output],[o],[Name of the output file (pass '-' for stdout)],[-])
@@ -12,16 +12,16 @@ version=1.4.2
 
 # ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
-### START OF CODE GENERATED BY Argbash v1.4.2 one line above ###
+### START OF CODE GENERATED BY Argbash v2.0.0 one line above ###
 # Argbash is a bash code generator used to get arguments parsing right.
 # Argbash is FREE SOFTWARE, know your rights: https://github.com/matejak/argbash
 
 # THE DEFAULTS INITIALIZATION --- POSITIONALS
 # THE DEFAULTS INITIALIZATION --- OPTIONALS
-_ARG_OUTPUT="-"
-_ARG_STANDALONE=off
-_ARG_SEARCH=(".")
-_ARG_DEBUG=""
+_arg_output="-"
+_arg_standalone=off
+_arg_search=(".")
+_arg_debug=""
 
 # THE PRINT HELP FUNCION
 print_help ()
@@ -29,10 +29,10 @@ print_help ()
 	echo "Argbash is an argument parser generator for Bash."
 	printf 'Usage: %s [-o|--output <arg>] [--(no-)standalone] [-I|--search] [--debug <arg>] [-v|--version] [-h|--help] <input>\n' "$0"
 	printf "\t<input>: The input template file\n"
-	printf "\t-o,--output: Name of the output file (pass '-' for stdout) (default: '%s')\n" "${_ARG_OUTPUT}"
-	printf "\t--standalone,--no-standalone: Whether the parsing code is in a standalone file. (%s by default)\n" "${_ARG_STANDALONE}"
-	printf "\t-I,--search: Directories to search for the wrapped scripts (directory of the template will be added to the end of the list) (default array: (%s) )\n" "${_ARG_SEARCH[*]}"
-	printf "\t--debug: (developer option) Tell autom4te to trace a macro (default: '%s')\n" "${_ARG_DEBUG}"
+	printf "\t-o,--output: Name of the output file (pass '-' for stdout) (default: '%s')\n" "${_arg_output}"
+	printf "\t--standalone,--no-standalone: Whether the parsing code is in a standalone file. (%s by default)\n" "${_arg_standalone}"
+	printf "\t-I,--search: Directories to search for the wrapped scripts (directory of the template will be added to the end of the list) (default array: (%s) )\n" "${_arg_search[*]}"
+	printf "\t--debug: (developer option) Tell autom4te to trace a macro (default: '%s')\n" "${_arg_debug}"
 	printf "\t-v,--version: Prints version\n"
 	printf "\t-h,--help: Prints help\n"
 }
@@ -44,24 +44,24 @@ do
 	case "$_key" in
 		-o|--output)
 			test $# -lt 2 && { echo "Missing value for the optional argument '$_key'." >&2; exit 1; }
-			_ARG_OUTPUT="$2"
+			_arg_output="$2"
 
 			shift
 			;;
 		--no-standalone|--standalone)
-			_ARG_STANDALONE="on"
+			_arg_standalone="on"
 
-			test "${1:0:5}" = "--no-" && _ARG_STANDALONE="off"
+			test "${1:0:5}" = "--no-" && _arg_standalone="off"
 			;;
 		-I|--search)
 			test $# -lt 2 && { echo "Missing value for the optional argument '$_key'." >&2; exit 1; }
-			_ARG_SEARCH+=("$2")
+			_arg_search+=("$2")
 
 			shift
 			;;
 		--debug)
 			test $# -lt 2 && { echo "Missing value for the optional argument '$_key'." >&2; exit 1; }
-			_ARG_DEBUG="$2"
+			_arg_debug="$2"
 
 			shift
 			;;
@@ -80,7 +80,7 @@ do
 	shift
 done
 
-_positional_names=('_ARG_INPUT' )
+_positional_names=('_arg_input' )
 test ${#_positionals[@]} -lt 1 && { ( echo "FATAL ERROR: Not enough positional arguments --- we require exactly 1, but got only ${#_positionals[@]}."; print_help ) >&2; exit 1; }
 test ${#_positionals[@]} -gt 1 && { ( echo "FATAL ERROR: There were spurious positional arguments --- we expect exactly 1, but got ${#_positionals[@]} (the last one was: '${_positionals[*]: -1}')."; print_help ) >&2; exit 1; }
 for (( ii = 0; ii < ${#_positionals[@]}; ii++))
@@ -89,7 +89,7 @@ do
 done
 
 # OTHER STUFF GENERATED BY Argbash
-SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || { echo "Couldn't determine the script's running directory, which probably matters, bailing out" >&2; exit 2; }
+script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || { echo "Couldn't determine the script's running directory, which probably matters, bailing out" >&2; exit 2; }
 
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
@@ -124,14 +124,14 @@ settle_wrapped_fname ()
 	for srcstem in "${_srcfiles[@]}"
 	do
 		_found=no
-		for searchdir in "${_ARG_SEARCH[@]}"
+		for searchdir in "${_arg_search[@]}"
 		do
 			test -f "$searchdir/$srcstem.m4" && { _found=yes; ext='.m4'; break; }
 			test -f "$searchdir/$srcstem.sh" && { _found=yes; ext='.sh'; break; }
 			test -f "$searchdir/$srcstem.sh" && { _found=yes; ext=''; break; }
 		done
 		# The last searchdir is a correct one
-		test $_found = yes || { echo "Couldn't find wrapped file of stem '$srcstem' in any of dirrectories: ${_ARG_SEARCH[*]}" >&2; exit 2; }
+		test $_found = yes || { echo "Couldn't find wrapped file of stem '$srcstem' in any of dirrectories: ${_arg_search[*]}" >&2; exit 2; }
 		_wrapped_defns="${_wrapped_defns}m4_define([_SCRIPT_$srcstem], [[$searchdir/$srcstem$ext]])"
 	done
 }
@@ -163,26 +163,26 @@ test -e $discard || discard=NUL
 
 set -o pipefail
 
-infile="$_ARG_INPUT"
+infile="$_arg_input"
 
-m4dir="$SCRIPT_DIR/../src"
-test -n "$_ARG_DEBUG" && DEBUG=('-t' "$_ARG_DEBUG")
+m4dir="$script_dir/../src"
+test -n "$_arg_debug" && DEBUG=('-t' "$_arg_debug")
 
 output_m4="$m4dir/output.m4"
-test "$_ARG_STANDALONE" = "on" && output_m4="$m4dir/output-standalone.m4"
+test "$_arg_standalone" = "on" && output_m4="$m4dir/output-standalone.m4"
 
 test -f "$infile" || { echo "'$infile' is supposed to be a file!" >&2; exit 1; }
-test -n "$_ARG_OUTPUT" || { echo "The output can't be blank - it is not a legal filename!" >&2; exit 1; }
-outfname="$_ARG_OUTPUT"
+test -n "$_arg_output" || { echo "The output can't be blank - it is not a legal filename!" >&2; exit 1; }
+outfname="$_arg_output"
 autom4te --version > "$discard" 2>&1 || { echo "You need the 'autom4te' utility (it comes with 'autoconf'), if you have bash, that one is an easy one to get." 2>&1; exit 1; }
-_ARG_SEARCH+=("$(dirname "$infile")")
+_arg_search+=("$(dirname "$infile")")
 _wrapped_defns=""
 
 # So let's settle the parsing code first. Hopefully we won't create a loop.
 parsing_code="$(get_parsing_code)"
 # Just if the original was m4, we replace .m4 with .sh
 test -n "$parsing_code" && parsing_code_out="${parsing_code:0:-2}sh"
-test "$_ARG_STANDALONE" = off && test -n "$parsing_code" && ($0 --standalone "$parsing_code" -o "$parsing_code_out")
+test "$_arg_standalone" = off && test -n "$parsing_code" && ($0 --standalone "$parsing_code" -o "$parsing_code_out")
 
 # We may use some of the wrapping stuff, so let's fill the _wrapped_defns
 settle_wrapped_fname
