Added the --strip option.

diff --git a/bin/argbash b/bin/argbash
--- a/bin/argbash
+++ b/bin/argbash
@@ -10,11 +10,13 @@
 # ARG_OPTIONAL_SINGLE([output],[o],[Name of the output file (pass '-' for stdout)],[-])
 # ARG_OPTIONAL_SINGLE([type],[t],[Output type to generate],[script])
 # ARG_OPTIONAL_BOOLEAN([library],[],[Whether the input file if the pure parsing library.])
+# ARG_OPTIONAL_SINGLE([strip],[],[Determines what to have in the output.],[none])
 # ARG_OPTIONAL_BOOLEAN([check-typos],[],[Whether to check for possible argbash macro typos],[on])
 # ARG_OPTIONAL_BOOLEAN([commented],[c],[Commented mode - include explanatory comments with the parsing code],[off])
 # ARG_OPTIONAL_REPEATED([search],[I],[Directories to search for the wrapped scripts (directory of the template will be added to the end of the list)],["."])
 # ARG_OPTIONAL_SINGLE([debug],[],[(developer option) Tell autom4te to trace a macro])
-# ARG_TYPE_GROUP_SET([type],[],[type],[script,completion])
+# ARG_TYPE_GROUP_SET([type],[type],[type],[script,completion])
+# ARG_TYPE_GROUP_SET([content],[content],[strip],[none,script,all])
 # ARG_DEFAULTS_POS([])
 # ARG_VERSION([echo "argbash v$version"])
 # ARG_HELP([Argbash is an argument parser generator for Bash.])
@@ -54,6 +56,16 @@ type()
 	done
 	die "Value '$_seeking' (of argument '$2') doesn't match the list of allowed values: 'script' and 'completion'" 4
 }
+content()
+{
+	local _allowed=("none" "script" "all")
+	local _seeking="$1"
+	for element in "${_allowed[@]}"
+	do
+		test "$element" = "$_seeking" && echo "$element" && return 0
+	done
+	die "Value '$_seeking' (of argument '$2') doesn't match the list of allowed values: 'none', 'script' and 'all'" 4
+}
 
 # THE DEFAULTS INITIALIZATION - POSITIONALS
 _positionals=()
@@ -62,6 +74,7 @@ _arg_input=
 _arg_output="-"
 _arg_type="script"
 _arg_library="off"
+_arg_strip="none"
 _arg_check_typos="on"
 _arg_commented="off"
 _arg_search=(".")
@@ -70,11 +83,12 @@ _arg_debug=
 print_help ()
 {
 	printf '%s\n' "Argbash is an argument parser generator for Bash."
-	printf 'Usage: %s [-o|--output <arg>] [-t|--type <>] [--(no-)library] [--(no-)check-typos] [-c|--(no-)commented] [-I|--search <arg>] [--debug <arg>] [-v|--version] [-h|--help] <input>\n' "$0"
+	printf 'Usage: %s [-o|--output <arg>] [-t|--type <type>] [--(no-)library] [--strip <content>] [--(no-)check-typos] [-c|--(no-)commented] [-I|--search <arg>] [--debug <arg>] [-v|--version] [-h|--help] <input>\n' "$0"
 	printf '\t%s\n' "<input>: The input template file (pass '-' for stdin)"
 	printf '\t%s\n' "-o,--output: Name of the output file (pass '-' for stdout) (default: '-')"
 	printf '\t%s\n' "-t,--type: Output type to generate (one of 'script' and 'completion'; default: 'script')"
 	printf '\t%s\n' "--library,--no-library: Whether the input file if the pure parsing library. (off by default)"
+	printf '\t%s\n' "--strip: Determines what to have in the output. (one of 'none', 'script' and 'all'; default: 'none')"
 	printf '\t%s\n' "--check-typos,--no-check-typos: Whether to check for possible argbash macro typos (on by default)"
 	printf '\t%s\n' "-c,--commented,--no-commented: Commented mode - include explanatory comments with the parsing code (off by default)"
 	printf '\t%s\n' "-I,--search: Directories to search for the wrapped scripts (directory of the template will be added to the end of the list) (default array: (\".\") )"
@@ -114,6 +128,14 @@ parse_commandline ()
 			--no-library|--library)
 				_arg_library="on"
 				test "${1:0:5}" = "--no-" && _arg_library="off"
+				;;
+			--strip)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_strip="$(content "$2" "strip")" || exit 1
+				shift
+				;;
+			--strip=*)
+				_arg_strip="$(content "${_key##--strip=}" "strip")" || exit 1
 				;;
 			--no-check-typos|--check-typos)
 				_arg_check_typos="on"
@@ -201,6 +223,7 @@ script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || die "Couldn't dete
 # Validation of values
 
 
+
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
 
@@ -284,8 +307,8 @@ assert_m4_files_are_readable()
 # The main function that generates the parsing script body
 # $1: The input file
 # $2: The output file
-# $2: The argument type
-do_stuff ()
+# $3: The argument type
+do_stuff()
 {
 	local _pass_also="$_wrapped_defns" input prefix_len _ret
 	test "$_arg_commented" = on && _pass_also="${_pass_also}m4_define([COMMENT_OUTPUT])"
@@ -310,7 +333,7 @@ do_stuff ()
 }
 
 # Fills content to variable _wrapped_defns --- where are scripts of given stems
-settle_wrapped_fname ()
+settle_wrapped_fname()
 {
 	# Get arguments to ARGBASH_WRAP
 	# Based on http://stackoverflow.com/a/19772067/592892
@@ -341,7 +364,7 @@ settle_wrapped_fname ()
 # 2. If the file exists, finish (OK).
 # 3. If the .m4 file exists, finish (OK)
 # 4. Something is wrong
-function get_parsing_code
+get_parsing_code()
 {
 	local _shfile _m4file _newerfile
 	# Get the argument of INCLUDE_PARSING_CODE
@@ -388,8 +411,15 @@ fi
 m4dir="$script_dir/../src"
 test -n "$_arg_debug" && DEBUG=('-t' "$_arg_debug")
 
-output_m4="$m4dir/output.m4"
-test "$_arg_library" = "on" && output_m4="$m4dir/output-standalone.m4"
+output_m4="$m4dir/output-strip-none.m4"
+test "$_arg_library" = "on" && { echo "The --library option is deprecated, use --strip script" next time >&2; _arg_strip="script"; }
+if test "$_arg_strip" = "script"
+then
+	output_m4="$m4dir/output-strip-script.m4"
+elif test "$_arg_strip" = "all"
+then
+	output_m4="$m4dir/output-strip-all.m4"
+fi
 
 test -f "$infile" || _PRINT_HELP=yes die "argument '$infile' is supposed to be a file!" 1
 test -n "$_arg_output" || { echo "The output can't be blank - it is not a legal filename!" >&2; exit 1; }
