Generalized assignment of positional args.

diff --git a/bin/argbash-1to2 b/bin/argbash-1to2
--- a/bin/argbash-1to2
+++ b/bin/argbash-1to2
@@ -105,6 +105,7 @@ handle_passed_args_count()
 
 assign_positional_args()
 {
+	local _positional_name
 	_positional_names=('_arg_input' )
 	_our_args=$((${#_positionals[@]} - ${#_positional_names[@]}))
 	for ((ii = 0; ii < _our_args; ii++))
@@ -112,15 +113,17 @@ assign_positional_args()
 		_positional_names+=("_arg_input[$((ii + 1))]")
 	done
 
-	for (( ii = 0; ii < ${#_positionals[@]}; ii++))
+	for _positional_name in "${_positional_names[@]}"
 	do
-		eval "${_positional_names[ii]}=\${_positionals[ii]}" || die "Error during argument parsing, possibly an Argbash bug." 1
+		test $# -gt 0 || break
+		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
+		shift
 	done
 }
 
 parse_commandline "$@"
 handle_passed_args_count
-assign_positional_args
+assign_positional_args "${_positionals[@]}"
 
 # OTHER STUFF GENERATED BY Argbash
 
