Added --mode option to argbash-init

diff --git a/bin/argbash-init b/bin/argbash-init
--- a/bin/argbash-init
+++ b/bin/argbash-init
@@ -8,6 +8,7 @@ version=2.2.1a
 # ARG_OPTIONAL_REPEATED([opt],[],[Add an single-valued optional argument])
 # ARG_OPTIONAL_REPEATED([opt-bool],[],[Add an optional boolean argument])
 # ARG_OPTIONAL_REPEATED([wrap],[],[What script(s) to wrap])
+# ARG_OPTIONAL_SINGLE([mode],[m],[The slider between feature-rich and simple script.],[default])
 # ARG_VERSION([echo "argbash-init v$version"])
 # ARG_HELP([Make a template for scripts.])
 
@@ -35,12 +36,13 @@ _arg_pos=()
 _arg_opt=()
 _arg_opt_bool=()
 _arg_wrap=()
+_arg_mode="default"
 
 # THE PRINT HELP FUNCION
 print_help ()
 {
 	echo "Make a template for scripts."
-	printf 'Usage: %s [-s|--separate] [--(no-)hints] [--pos <arg>] [--opt <arg>] [--opt-bool <arg>] [--wrap <arg>] [-v|--version] [-h|--help] [<output>]\n' "$0"
+	printf 'Usage: %s [-s|--separate] [--(no-)hints] [--pos <arg>] [--opt <arg>] [--opt-bool <arg>] [--wrap <arg>] [-m|--mode <arg>] [-v|--version] [-h|--help] [<output>]\n' "$0"
 	printf "\t%s\n" "<output>: Name of the output template (default: '""-""')"
 	printf "\t%s\n" "-s,--separate: Separate the parsing logic (specify two times for complete separation)"
 	printf "\t%s\n" "--hints,--no-hints: Whether to write hints to the script template (off by default)"
@@ -48,6 +50,7 @@ print_help ()
 	printf "\t%s\n" "--opt: Add an single-valued optional argument (empty by default)"
 	printf "\t%s\n" "--opt-bool: Add an optional boolean argument (empty by default)"
 	printf "\t%s\n" "--wrap: What script(s) to wrap (empty by default)"
+	printf "\t%s\n" "-m,--mode: The slider between feature-rich and simple script. (default: '"default"')"
 	printf "\t%s\n" "-v,--version: Prints version"
 	printf "\t%s\n" "-h,--help: Prints help"
 }
@@ -103,6 +106,16 @@ do
 				shift
 			fi
 			_arg_wrap+=("$_val")
+			;;
+		-m|--mode|--mode=*)
+			_val="${_key##--mode=}"
+			if test "$_val" = "$_key"
+			then
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_val="$2"
+				shift
+			fi
+			_arg_mode="$_val"
 			;;
 		-v|--version)
 			echo "argbash-init v$version"
@@ -217,6 +230,14 @@ do_args()
 
 do_args_footer()
 {
+	if test "$_arg_mode" = "full"
+	then
+		echo 'ARGBASH_SET_DELIM([ =])'
+		echo 'ARG_DEFAULTS_POS'
+	elif test "$_arg_mode" = "minimal"
+	then
+		echo 'ARGBASH_SET_DELIM([ ])'
+	fi
 	echo "# ARG_HELP([<The general help message of my script>])"
 	echo "# ARGBASH_GO"
 }
@@ -284,17 +305,24 @@ if test "$outfname" = '-'
 then
 	do_stuff 'script'
 else
-	test "$_arg_separate" = 0 && do_stuff 'script' > "$outfname" || parse_fname_stem="$(echo "${outfname}" | sed -e 's/\.\(sh\|m4\)$//')-parsing"
-	# IMPORTANT NOTION:
-	# do_stuff has to be called FIRST, because it sets the _variables array content as its side-effect
-	test "$_arg_separate" = 1 && {
-		do_stuff 'lib' > "${parse_fname_stem}.m4"
-		do_script_assisted > "$outfname"
-	}
-	test "$_arg_separate" = 2 && {
-		do_stuff 'lib'  > "${parse_fname_stem}.m4"
-		do_script_bare > "$outfname"
-	}
+	if test "$_arg_separate" = 0
+	then
+		do_stuff 'script' > "$outfname"
+	else
+		parse_fname_stem="$(echo "${outfname}" | sed -e 's/\.\(sh\|m4\)$//')-parsing"
+
+		# IMPORTANT NOTION:
+		# do_stuff has to be called FIRST, because it sets the _variables array content as its side-effect
+		if test "$_arg_separate" = 1
+		then
+			do_stuff 'lib' > "${parse_fname_stem}.m4"
+			do_script_assisted > "$outfname"
+		else
+			test "$_arg_separate" = 2 || echo "The greatest separation value is 2, got $_arg_separate" >&2
+			do_stuff 'lib'  > "${parse_fname_stem}.m4"
+			do_script_bare > "$outfname"
+		fi
+	fi
 	chmod a+x "$outfname"
 fi
 
