Begun putting Argbash stuff into bash functions.

diff --git a/bin/argbash b/bin/argbash
--- a/bin/argbash
+++ b/bin/argbash
@@ -147,14 +147,22 @@ do
 	shift
 done
 
-_required_args_string="'input'"
-test ${#_positionals[@]} -lt 1 && _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 1 (namely: $_required_args_string), but got only ${#_positionals[@]}." 1
-test ${#_positionals[@]} -gt 1 && _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 1 (namely: $_required_args_string), but got ${#_positionals[@]} (the last one was: '${_positionals[*]: -1}')." 1
+handle_passed_args_count ()
+{
+	_required_args_string="'input'"
+	test ${#_positionals[@]} -lt 1 && _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 1 (namely: $_required_args_string), but got only ${#_positionals[@]}." 1
+	test ${#_positionals[@]} -gt 1 && _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 1 (namely: $_required_args_string), but got ${#_positionals[@]} (the last one was: '${_positionals[*]: -1}')." 1
+}
 _positional_names=('_arg_input' )
-for (( ii = 0; ii < ${#_positionals[@]}; ii++))
-do
-	eval "${_positional_names[ii]}=\${_positionals[ii]}" || die "Error during argument parsing, possibly an Argbash bug." 1
-done
+assign_positional_args ()
+{
+	for (( ii = 0; ii < ${#_positionals[@]}; ii++))
+	do
+		eval "${_positional_names[ii]}=\${_positionals[ii]}" || die "Error during argument parsing, possibly an Argbash bug." 1
+	done
+}
+handle_passed_args_count
+assign_positional_args
 
 # OTHER STUFF GENERATED BY Argbash
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || die "Couldn't determine the script's running directory, which probably matters, bailing out" 2
diff --git a/bin/argbash-1to2 b/bin/argbash-1to2
--- a/bin/argbash-1to2
+++ b/bin/argbash-1to2
@@ -88,19 +88,26 @@ do
 	shift
 done
 
-_required_args_string="'input'"
-test ${#_positionals[@]} -lt 1 && _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${#_positionals[@]}." 1
-
+handle_passed_args_count ()
+{
+	_required_args_string="'input'"
+	test ${#_positionals[@]} -lt 1 && _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${#_positionals[@]}." 1
+}
 _positional_names=('_arg_input' )
 _our_args=$((${#_positionals[@]} - ${#_positional_names[@]}))
 for ((ii = 0; ii < _our_args; ii++))
 do
 	_positional_names+=("_arg_input[$((ii + 1))]")
 done
-for (( ii = 0; ii < ${#_positionals[@]}; ii++))
-do
-	eval "${_positional_names[ii]}=\${_positionals[ii]}" || die "Error during argument parsing, possibly an Argbash bug." 1
-done
+assign_positional_args ()
+{
+	for (( ii = 0; ii < ${#_positionals[@]}; ii++))
+	do
+		eval "${_positional_names[ii]}=\${_positionals[ii]}" || die "Error during argument parsing, possibly an Argbash bug." 1
+	done
+}
+handle_passed_args_count
+assign_positional_args
 
 # OTHER STUFF GENERATED BY Argbash
 
diff --git a/bin/argbash-init b/bin/argbash-init
--- a/bin/argbash-init
+++ b/bin/argbash-init
@@ -173,12 +173,20 @@ do
 	shift
 done
 
-test ${#_positionals[@]} -gt 1 && _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect between 0 and 1, but got ${#_positionals[@]} (the last one was: '${_positionals[*]: -1}')." 1
+handle_passed_args_count ()
+{
+	test ${#_positionals[@]} -gt 1 && _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect between 0 and 1, but got ${#_positionals[@]} (the last one was: '${_positionals[*]: -1}')." 1
+}
 _positional_names=('_arg_output' )
-for (( ii = 0; ii < ${#_positionals[@]}; ii++))
-do
-	eval "${_positional_names[ii]}=\${_positionals[ii]}" || die "Error during argument parsing, possibly an Argbash bug." 1
-done
+assign_positional_args ()
+{
+	for (( ii = 0; ii < ${#_positionals[@]}; ii++))
+	do
+		eval "${_positional_names[ii]}=\${_positionals[ii]}" || die "Error during argument parsing, possibly an Argbash bug." 1
+	done
+}
+handle_passed_args_count
+assign_positional_args
 
 # OTHER STUFF GENERATED BY Argbash
 # Validation of values
