Improved code, added bunch of tests

diff --git a/tests/regressiontests/reverse b/tests/regressiontests/reverse
--- a/tests/regressiontests/reverse
+++ b/tests/regressiontests/reverse
@@ -1,9 +1,27 @@
 #!/bin/bash
 
-"$@"
+if test -n "$ERROR"
+then
+	"$@" 2> /dev/null
+else
+	"$@"
+fi
+
 if test $? = 0 
 then
+	echo "Error expected, but it did not occur" >&2
 	exit 1
-else
+# We don't care what the error string should look like
+elif test -z "$ERROR"
+then
 	exit 0
+# We examine the error string
+else
+	if "$@" 2>&1 | grep -q "$ERROR"
+	then
+		exit 0
+	else
+		echo "Error occured, but not a good one:" >&2
+		"$@"
+	fi
 fi
